apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my
  name: my
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my
    spec:
      containers:
      - name: httpd
        image: taraspetryk/httpd:placeholder
        #command:
        #- sh
        #- -euc
        #- sleep 90
        #command: ["/bin/sh","-c"]
        envFrom:
        - configMapRef:
            name: my-config
        - secretRef:
            name: mysecret
        command: ['/bin/sh', '-c', 'sleep infinity']
        resources: {}
status: {}
