apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my
  name: my
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my
    spec:
      containers:
      - image: taraspetryk/httpd:placeholder
        name: httpd
        resources: {}
status: {}
